name: split-tests-by-timings
description: Split test files based on JUnit XML reports.
inputs:
  reports:
    description: Path to directory where JUnit XML reports are stored.
    required: true
  glob:
    description: Glob pattern to search test files.
    required: false
    default: ""
  globs:
    description: Glob patterns to search test files. Use a multiline string to pass multiple patterns.
    required: false
    default: ""
  index:
    description: 0-based index of test node.
    required: true
  total:
    description: Total count of test nodes.
    required: true
  working-directory:
    description: Working directory to run the action.
    required: false
    default: .
  architecture:
    description: CPU architecture
    required: false
    default: x86_64
outputs:
  paths:
    description: Paths of test files to run.
    value: ${{ steps.split-tests.outputs.paths }}
runs:
  using: composite
  steps:
    - run: |
        curl -L --output split-test https://github.com/mtsmfm/split-test/releases/download/v1.1.0/split-test-${{ inputs.architecture }}-unknown-linux-gnu
        chmod +x split-test
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - id: split-tests
      run: "${GITHUB_ACTION_PATH}/scripts/split-tests"
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        INPUT_REPORTS: ${{ inputs.reports }}
        INPUT_INDEX: ${{ inputs.index }}
        INPUT_TOTAL: ${{ inputs.total }}
        INPUT_GLOB: ${{ inputs.glob }}
        INPUT_GLOBS: ${{ inputs.globs }}
    - run: rm split-test
      shell: bash
      working-directory: ${{ inputs.working-directory }}
branding:
  color: green
  icon: grid
